### ISSUE TITLE
access to sysv's symbol table

### ISSUE THREAD

**Issue by aep** [mdsteele/rust-ar#3]
since i'm writing a linker ( https://github.com/aep/elfkit )
it would be nice to get access to the sysv symbol lookup table

**Comment by mdsteele** [comment]
Seems reasonable.  What kind of API would be most useful to you?  The simplest option would be to just have the `Archive` return the raw symbol table data as an `Entry` -- just like it returns all the other entries -- instead of skipping over it, and leave it up to the caller to parse.  However, I imagine it would be more useful to have the library actually parse the symbol table, and then provide methods for iterating over the symbols and for jumping to the appropriate `Entry` for a given symbol (if the underlying reader implements the `Seek` trait).  What do you think?

**Comment by aep** [comment]
i'm perfectly fine with getting the raw data, but since this is ar specific, it might make sense to add the parser to rust-ar.

In my case i'd iterate over them and add each to a bloom filter, so anything other than a raw &[u8] to the symbol name is wasted here. Not sure how to accommodate for that in a nice interface.

**Comment by mdsteele** [comment]
Okay, so sounds like for now you just need the list of symbol names, not the entry offsets for each symbol.

I've added an API for iterating over the symbols in the table in 4831b8d.  See what you think.

**Comment by aep** [comment]
that's a smart api returning the &str in an iterator, pretty good.
For me this is already useful, but i really think not exposing the entry offsets is a bit of a shame, since those might come in handy for someone else.

**Comment by aep** [comment]
i just realized you're  parsing the symbol as utf8, that's unfortunately quite expensive. i really think they should be returned as &[u8]

**Comment by aep** [comment]
@mdsteele are we stuck with this?

**Comment by mdsteele** [comment]
You're probably right, `&[u8]` would be more appropriate.  It's not clear that the symbols have to be UTF-8 anyway.

The library also currently uses `String` for file identifiers, but I'm not sure that those are necessarily UTF-8 either, so perhaps those should be `&[u8]` as well.  What do you think?

**Comment by aep** [comment]
absolutely, i'm all for full &[u8]

**Comment by mdsteele** [comment]
Sounds good.  I just pushed some new changes to make everything `&[u8]`.  If those look good to you, I can publish a new version to crates.io.

**Comment by aep** [comment]
tested and works for me. thanks!

**Comment by mdsteele** [comment]
Thanks!  [Version 0.5.0](https://crates.io/crates/ar/0.5.0) has been published.
